### PR TITLE
Fix collection filter off-by-one error

### LINKED ISSUE #182: wk_collection creates null geometry collection for sfc objects
When creating a collection from an sfc object using wk an error occurs. 

``` r
x <- sf::st_multipoint(matrix(runif(10, -90, 90), ncol = 2))
wk::wk_collection(sf::st_sfc(x)) 
#> Geometry set for 1 feature 
#> Geometry type: GEOMETRYCOLLECTION
#> Dimension:     XY
#> Bounding box:  xmin: -62.02268 ymin: -60.93753 xmax: 59.29722 ymax: 50.98169
#> CRS:           NA
#> Error in UseMethod("st_as_text"): no applicable method for 'st_as_text' applied to an object of class "NULL"
```

### PR DESCRIPTION
**Pull request by anthonynorth**
Fixes the off-by-one part_id bug in the collection filter. Appears to have only affected the sfc_writer

Fixes #182

### CODE REVIEW

File: tests/testthat/test-make.R [hunk 1]
```diff
@@ -289,3 +289,77 @@ test_that("wk_collection_filter() errors for handlers that return WK_ABORT_FEATU
     "does not support WK_ABORT_FEATURE"
   )
 })
+
+test_that("wk_collection() works with sfc", {
+  points_xy <- xy(1:64, 1:64)
```
Comment (paleolimbot) [inline tests/testthat/test-make.R:294]: I think this needs `skip_if_not_installed("sf")`

**Review by paleolimbot — APPROVED** [review]
Just one nit! Thank you!
